# Travis CI build file for OpenAPI Compiler, including Go and Swift plugins

# Use Ubuntu 14.04
dist: trusty

sudo: false

language: go

go:
- "1.13"

script:
  - export GO111MODULE=on
  - go get ./...
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
